package dev.abbasian.exoboost.domain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class SubtitleTrack(
    val id: String,
    val language: String,
    val languageCode: String,
    val url: String,
    val format: SubtitleFormat,
    val source: SubtitleSource,
    val isDefault: Boolean = false,
    val isForced: Boolean = false,
    val isAutoGenerated: Boolean = false,
) : Parcelable

enum class SubtitleFormat(
    val extension: String,
    val mimeType: String,
) {
    SRT("srt", "application/x-subrip"),
    VTT("vtt", "text/vtt"),
    ASS("ass", "text/x-ssa"),
    SSA("ssa", "text/x-ssa"),
    TTML("ttml", "application/ttml+xml"),
}

enum class SubtitleSource {
    EMBEDDED,
    EXTERNAL,
    OPENSUBTITLES,
    YIFY,
    PODNAPISI,
    SUBSCENE,
    CUSTOM,
}

@Parcelize
data class SubtitleStyle(
    val textSize: SubtitleSize = SubtitleSize.MEDIUM,
    val textColor: Int = 0xFFFFFFFF.toInt(),
    val backgroundColor: Int = 0x80000000.toInt(),
    val backgroundOpacity: Float = 0.5f,
    val outlineColor: Int = 0xFF000000.toInt(),
    val outlineWidth: Float = 2f,
    val fontFamily: String? = null,
    val isBold: Boolean = false,
    val isItalic: Boolean = false,
) : Parcelable

enum class SubtitleSize(
    val scale: Float,
    val labelKey: String,
) {
    VERY_SMALL(0.6f, "very_small"),
    SMALL(0.8f, "small"),
    MEDIUM(1.0f, "medium"),
    LARGE(1.3f, "large"),
    VERY_LARGE(1.6f, "very_large"),
}

data class SubtitleCue(
    val startTimeMs: Long,
    val endTimeMs: Long,
    val text: String,
    val position: Float? = null,
    val line: Int? = null,
)

data class ParsedSubtitle(
    val cues: List<SubtitleCue>,
    val format: SubtitleFormat,
    val language: String? = null,
)

data class SubtitleQuery(
    val videoName: String,
    val videoHash: String? = null,
    val imdbId: String? = null,
    val season: Int? = null,
    val episode: Int? = null,
    val language: String = "en",
)

sealed class SubtitleDownloadResult {
    data class Success(
        val subtitle: SubtitleTrack,
        val content: String,
    ) : SubtitleDownloadResult()

    data class Error(
        val message: String,
        val cause: Throwable? = null,
    ) : SubtitleDownloadResult()

    object Loading : SubtitleDownloadResult()
}
